// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdrkjywbdiyiddyouhpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkcmtqeXdiZGl5aWRkeW91aHBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMTg0NzksImV4cCI6MjA2Mzc5NDQ3OX0.LOogw3UrOzxUnSEmISNtalEprhOsd9pWeB_15FvgZA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);